name: ARTClub

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install  # Or any other package manager commands
        
    - name: Run tests
      run: |
        npm test     # Or any other test commands
